
import { Skill } from "@/types/StatusTypes";

// Export the default skills
export const defaultSkills: Skill[] = [
  // Weapons branch - 10 skills
  {
    id: "pomodoro",
    name: "Pomodoro Master",
    description: "Complete 5 daily focused sessions for 7 days",
    branch: "weapons",
    tier: 1,
    level: 0,
    maxLevel: 3,
    unlocked: true,
    xpReward: 15,
    icon: "sword",
    position: { x: 50, y: 50 },
    connections: ["deep-work", "flow-state"]
  },
  {
    id: "deep-work",
    name: "Deep Work",
    description: "Complete 2 hours of uninterrupted work for 5 days",
    branch: "weapons",
    tier: 2,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 20,
    icon: "target",
    position: { x: 45, y: 35 },
    connections: ["flow-state", "time-blocking"]
  },
  {
    id: "flow-state",
    name: "Flow State",
    description: "Enter flow state 10 times",
    branch: "weapons",
    tier: 2,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 20,
    icon: "zap",
    position: { x: 55, y: 35 },
    connections: ["rapid-learning"]
  },
  {
    id: "time-blocking",
    name: "Time Blocking",
    description: "Plan your day with time blocks for 14 days",
    branch: "weapons",
    tier: 3,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 25,
    icon: "target",
    position: { x: 40, y: 25 },
    connections: ["habit-stacking"]
  },
  {
    id: "rapid-learning",
    name: "Rapid Learning",
    description: "Learn a new concept in under an hour 5 times",
    branch: "weapons",
    tier: 3,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 25,
    icon: "flame",
    position: { x: 60, y: 25 },
    connections: ["mental-models"]
  },
  {
    id: "habit-stacking",
    name: "Habit Stacking",
    description: "Stack 3 habits successfully for 21 days",
    branch: "weapons",
    tier: 4,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 30,
    icon: "sword",
    position: { x: 35, y: 20 },
    connections: ["deliberate-practice"]
  },
  {
    id: "mental-models",
    name: "Mental Models",
    description: "Apply 5 mental models to solve problems",
    branch: "weapons",
    tier: 4,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 30,
    icon: "diamond",
    position: { x: 65, y: 20 },
    connections: ["second-brain"]
  },
  {
    id: "deliberate-practice",
    name: "Deliberate Practice",
    description: "Practice with focused improvement for 30 days",
    branch: "weapons",
    tier: 5,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 40,
    icon: "target",
    position: { x: 32, y: 12 },
    connections: ["expert-level"]
  },
  {
    id: "second-brain",
    name: "Second Brain",
    description: "Build a personal knowledge system with 50+ notes",
    branch: "weapons",
    tier: 5,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 40,
    icon: "zap",
    position: { x: 68, y: 12 },
    connections: ["expert-level"]
  },
  {
    id: "expert-level",
    name: "Expert Level",
    description: "Reach proficiency in a skill that puts you in the top 5%",
    branch: "weapons",
    tier: 6,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 50,
    icon: "star",
    position: { x: 50, y: 8 },
    connections: []
  },
  
  // Defense branch - 10 skills
  {
    id: "meditation",
    name: "Mind Clarity",
    description: "Meditate for 10 minutes daily for 10 days",
    branch: "defense",
    tier: 1,
    level: 0,
    maxLevel: 3,
    unlocked: true,
    xpReward: 15,
    icon: "shield",
    position: { x: 20, y: 50 },
    connections: ["exercise", "sleep-hygiene"]
  },
  {
    id: "exercise",
    name: "Physical Strength",
    description: "Exercise 3 times per week for 4 weeks",
    branch: "defense",
    tier: 2,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 20,
    icon: "shield",
    position: { x: 15, y: 35 },
    connections: ["nutrition"]
  },
  {
    id: "sleep-hygiene",
    name: "Sleep Hygiene",
    description: "Maintain a consistent sleep schedule for 21 days",
    branch: "defense",
    tier: 2,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 20,
    icon: "circle",
    position: { x: 25, y: 35 },
    connections: ["stress-management"]
  },
  {
    id: "nutrition",
    name: "Balanced Nutrition",
    description: "Track and maintain balanced meals for 14 days",
    branch: "defense",
    tier: 3,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 25,
    icon: "shield",
    position: { x: 10, y: 25 },
    connections: ["immune-strength"]
  },
  {
    id: "stress-management",
    name: "Stress Management",
    description: "Apply 3 stress-reduction techniques for 30 days",
    branch: "defense",
    tier: 3,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 25,
    icon: "shield",
    position: { x: 30, y: 25 },
    connections: ["emotional-mastery"]
  },
  {
    id: "immune-strength",
    name: "Immune Strength",
    description: "Boost immune system with supplements and self-care",
    branch: "defense",
    tier: 4,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 30,
    icon: "shield",
    position: { x: 5, y: 20 },
    connections: ["resilience"]
  },
  {
    id: "emotional-mastery",
    name: "Emotional Mastery",
    description: "Practice emotional intelligence daily for 30 days",
    branch: "defense",
    tier: 4,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 30,
    icon: "shield",
    position: { x: 35, y: 20 },
    connections: ["mindfulness"]
  },
  {
    id: "resilience",
    name: "Resilience",
    description: "Bounce back from setbacks stronger 5 times",
    branch: "defense",
    tier: 5,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 40,
    icon: "shield",
    position: { x: 8, y: 12 },
    connections: ["armor-mastery"]
  },
  {
    id: "mindfulness",
    name: "Mindfulness",
    description: "Practice being present in all activities for 21 days",
    branch: "defense",
    tier: 5,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 40,
    icon: "shield",
    position: { x: 32, y: 12 },
    connections: ["armor-mastery"]
  },
  {
    id: "armor-mastery",
    name: "Armor Mastery",
    description: "Develop unshakable mental defenses against life's challenges",
    branch: "defense",
    tier: 6,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 50,
    icon: "star",
    position: { x: 20, y: 8 },
    connections: []
  },
  
  // Magic branch - 10 skills
  {
    id: "reading",
    name: "Book Worm",
    description: "Read 20 pages daily for 14 days",
    branch: "magic",
    tier: 1,
    level: 0,
    maxLevel: 3,
    unlocked: true,
    xpReward: 15,
    icon: "wand",
    position: { x: 80, y: 50 },
    connections: ["language-learning", "active-learning"]
  },
  {
    id: "language-learning",
    name: "Language Learner",
    description: "Practice a language for 15 minutes daily for 30 days",
    branch: "magic",
    tier: 2,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 20,
    icon: "book",
    position: { x: 75, y: 35 },
    connections: ["teaching-others"]
  },
  {
    id: "active-learning",
    name: "Active Learning",
    description: "Take structured notes on 10 topics",
    branch: "magic",
    tier: 2,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 20,
    icon: "book",
    position: { x: 85, y: 35 },
    connections: ["course-completion"]
  },
  {
    id: "teaching-others",
    name: "Teaching Others",
    description: "Teach a concept to someone else 5 times",
    branch: "magic",
    tier: 3,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 25,
    icon: "wand",
    position: { x: 70, y: 25 },
    connections: ["knowledge-synthesis"]
  },
  {
    id: "course-completion",
    name: "Course Completion",
    description: "Complete 3 online courses",
    branch: "magic",
    tier: 3,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 25,
    icon: "book",
    position: { x: 90, y: 25 },
    connections: ["creative-thinking"]
  },
  {
    id: "knowledge-synthesis",
    name: "Knowledge Synthesis",
    description: "Combine ideas from different domains 10 times",
    branch: "magic",
    tier: 4,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 30,
    icon: "wand",
    position: { x: 65, y: 20 },
    connections: ["critical-thinking"]
  },
  {
    id: "creative-thinking",
    name: "Creative Thinking",
    description: "Generate 50 unique ideas for problems",
    branch: "magic",
    tier: 4,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 30,
    icon: "wand",
    position: { x: 95, y: 20 },
    connections: ["problem-solving"]
  },
  {
    id: "critical-thinking",
    name: "Critical Thinking",
    description: "Analyze and evaluate 10 complex situations",
    branch: "magic",
    tier: 5,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 40,
    icon: "wand",
    position: { x: 68, y: 12 },
    connections: ["enlightenment"]
  },
  {
    id: "problem-solving",
    name: "Problem Solving",
    description: "Solve 20 challenging problems using structured methods",
    branch: "magic",
    tier: 5,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 40,
    icon: "wand",
    position: { x: 92, y: 12 },
    connections: ["enlightenment"]
  },
  {
    id: "enlightenment",
    name: "Enlightenment",
    description: "Achieve wisdom by synthesizing all knowledge domains",
    branch: "magic",
    tier: 6,
    level: 0,
    maxLevel: 3,
    unlocked: false,
    xpReward: 50,
    icon: "star",
    position: { x: 80, y: 8 },
    connections: []
  }
];
